ci: require successful build in pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,8 +2,14 @@
 # vim: filetype=sh
 #───────────────────────────────────────────────────────────────────────────────
 
-# block if there are any issues reported by biome
+# INFO block if there are any issues reported by biome or if building fails
 echo
-print "\033[1;34mPre-Commit Hook: Biome\033[0m"
+print "\033[1;34mPre-Commit Hook\e[0m"
+
+print "\033[1;35mBiome Check\033[0m"
 biome check --log-kind="compact" "$(git rev-parse --show-toplevel)" || exit 1
+
+printf "\033[1;35mBuild\033[0m"
+node esbuild.config.mjs || exit 1
+
 echo
